version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: marketplace-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: marketplace-backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/marketplace
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: marketplace-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: